sudo: required
services:
  - docker

before_install:
  - docker build -t daviddonikapanjaitan/docker-react -f Dockerfile.dev .

script:
  - docker run daviddonikapanjaitan/docker-react npm run test -- --coverage