sudo: required
services:
  - docker

before_install:
  - docker build -t daviddonikapanjaitan/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true daviddonikapanjaitan/docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-876327780413"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY